deployment:
 tasks:
 - export DEPLOYPATH=/home/infost490f2305/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp login_page.php $DEPLOYPATH
 - /bin/cp handle_login.php $DEPLOYPATH
 - /bin/cp register_page.php $DEPLOYPATH
 - /bin/cp handle_register.php $DEPLOYPATH